# Page settings
baseurl = "https://aritan.org"
title = "Alex TV"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]
  
  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = "Alex"
  description = "My TV site"
  email = ""

  # Google Maps Javascript API Key (if not set will default to not passing a key)
  googleMapsApiKey = ""

  # Navigation
  [params.navigation]
    brand = "Alex TV"
    home = "Home"
    tv = "Movies & TV"
  
  # Hero section
  [params.hero]
    title = 'Awesome Movies, Decent TV'
    subtitle = 'Why pay to watch garbage when you can watch good stuff for free?'
  
